In [1]:
import numpy as np
import pandas as pd
import random
a=pd.read_csv('/content/drive/MyDrive/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [2]:
x=a.drop(columns=["price_range"],axis=1)
y=a["price_range"]
print(x)
print(y)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [3]:
minimum=np.min(y)
maximum=np.max(y)
print(minimum)
print(maximum)

0
3


In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x=scaler.fit_transform(x)
print(x)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.11623246 0.         0.72       ... 1.         0.         1.        ]
 [0.68002672 0.         0.96       ... 1.         1.         1.        ]
 [0.72144289 1.         0.2        ... 0.         1.         1.        ]
 ...
 [0.11422846 1.         0.         ... 0.         0.         0.        ]
 [0.05945224 1.         0.28       ... 0.         1.         0.        ]
 [0.25250501 1.         0.8        ... 1.         0.         1.        ]]
[[0.19505678 1.         0.92       ... 1.         1.         0.        ]
 [0.38877756 1.         0.36       ... 1.         1.         1.        ]
 [0.19505678 1.         0.56       ... 1.         1.         1.        ]
 ...
 [0.87641951 1.         0.04       ... 1.         1.         0.        ]
 [0.53907816 0.         0.32       ... 0.         1.         0.        ]
 [0.02672011 1.         0.72       ... 0.         0.         0.        ]]
679     0
705     2
1429    1
129     0
1476    2
       ..
1496    0
1760    1
974     0
1946    0
93      0
Na

In [6]:
data_set_2=pd.read_csv('/content/drive/MyDrive/heart (1).csv')
print(data_set_2)
x=data_set_2.drop(columns=["target"],axis=1)
y=data_set_2["target"]
print(x)
print(y)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
x=scaler.fit_transform(x)
print(x)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.27083333 1.         0.33333333 ... 1.         0.         0.66666667]
 [0.58333333 1.         0.33333333 ... 1.         0.25       0.66666667]
 [0.6875     1.         0.33333333 ... 0.5        0.25       1.        ]
 ...
 [0.5        1.         0.         ... 0.         0.         1.        ]
 [0.83333333 1.         1.         ... 0.5        0.25       0.66666667]
 [0.72916667 0.         0.         ... 1.         0.         0.66666667]]
[[0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.66666667 ... 1.         0.25       1.        ]
 [0.52083333 1.         0.         ... 0.5        0.25       0.66666667]
 ...
 [0.6875     0.         0.         ... 1.         0.         0.66666667]
 [0.52083333 0.         0.66666667 ... 0.5        0.         0.66666667]
 [0.85416667 1.         0.         ... 0.         0.         1.        ]]
132    1
287    0
226    0
97     1
189    0
      ..
236    0
83     1
169    0
106    1
110    1
Name: target,

In [9]:
x1=x_train[0]
x2=x_train[1]
x3=x_train[2]
x4=x_train[3]
x5=x_train[4]
x6=x_train[5]
x7=x_train[6]
x8=x_train[7]
x9=x_train[8]
x10=x_train[9]
x11=x_train[10]
x12=x_train[11]
x13=x_train[12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/(1+np.exp(-z))
    if (s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)
  return y_p
w1=random.randint(0,10)
w2=random.randint(0,10)
w3=random.randint(0,10)
w4=random.randint(0,10)
w5=random.randint(0,10)
w6=random.randint(0,10)
w7=random.randint(0,10)
w8=random.randint(0,10)
w9=random.randint(0,10)
w10=random.randint(0,10)
w11=random.randint(0,10)
w12=random.randint(0,10)
w13=random.randint(0,10)
b=random.randint(0,10)
print(perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
